import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import {AppProvider} from './lib/AppContext'


export const metadata = {
  title: 'Courses',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
        <Navbar />
        {children}
        <Footer />
        </AppProvider>
      </body>
    </html>
  )
}
